version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    volumes:
      - ./data:/data/db
    networks:
      - postgres-compose-network
      
  api:
    container_name: api-container
    build: .
    image: node:16
    working_dir: /usr/src/node-api
    command: bash -c "npm install --only=prod && npx typeorm migration:run && npm start"
    environment:
      - PG_DB_TYPE=postgres
      - PG_DB_HOST=postgres-compose
      - PG_DB_PORT=5432
      - PG_DB_USERNAME=postgres
      - PG_DB_PASSWORD=Postgres2019!
      - PG_DB_BASE=postgres
      - API_PORT=5050
    volumes:
      - ./backend/dist/:/usr/src/node-api/dist/
      - ./backend/package.json:/usr/src/node-api/package.json
      - ./backend/ormconfig.js:/usr/src/node-api/ormconfig.js
    ports:
      - "5050:5050"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network
    links:
      - postgres-compose
  front:
    container_name: front
    build: .
    image: node:16
    working_dir: /usr/src/front-api
    command: bash -c "npm install && npm run dev"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:5050/api
      
    volumes:
      - ./frontend/:/usr/src/front-api/
    ports:
      - "3002:3000"
    depends_on:
      - api
    networks:
      - postgres-compose-network
    links:
      - api   

networks: 
  postgres-compose-network:
    driver: bridge